### PR TITLE
bower integration, change of paths to static css/js

### PR DESCRIPTION
**Pull request by ThriceGood**
### bower

added a '.bowerrc' file and a 'bower.json' file to use bower as a package manager for JS and CSS.

`npm install  -g bower`

bower.json is the package file much like package.json for npm.

to create a bower.json file use `bower init`

the .bowerrc file just tells bower where to create the bower_components folder. I've put it inside the 'static' folder.

to install new bower dependencies use `bower install bootstrap --save ` this will add bootstrap to the bower.json file.

to install from the bower.json file, say when building from fresh, run `bower install` when in the same directory as the bower.json file. Same pattern as npm.

### static files

I've made some changes to the index.html file. Previously none of the JS or CSS was being loaded. was because the you have to programatically set which folder is for your static files. This is done in line 21 of 'app.s'

`app.use(express.static(path.join(__dirname, 'static')));`

you could add another line for the public folder but i suggest using the existing static folder.

the folder current structure for it is:

/app
..../static
......../bower_components  (bower installs to here)
......../js  (custom JS)
......../css  (custom CSS)

I've changed the paths in the script and link tags to go to the static folder, along with moving blog.css to static/css. Now the static files load up and we have a swell looking bootstrap blog!

if your happy with this we can merge these changes into master and work from there. And delete the public folder.

### Mongoose stuff

I added the db connection to the app.js file
Changed the 'model' folder to 'models'
Extended the Upload schema a bit
Changed the index route to call for the uploads
Added some example upload creation code to the post route

you can copy and paste that code into the index route and when you keep refreshing the page you see the uploads popping up

check the commit for more details

Alles gut?

### CODE REVIEW

**Comment by TOKUMK** [comment]
looks good, i would take out the bower stuff though

**Comment by TOKUMK** [comment]
fyi all scripts should be placed to the top of page to improve readability. a little nit picky, but if you are concerned about the website optimisation and performance load times with css and js libraries, a good tip is to use the defer tags to delay download time. this is better practice

**Comment by TOKUMK** [comment]
see here https://stackoverflow.com/questions/436411/where-should-i-put-script-tags-in-html-markup

**Comment by TOKUMK** [comment]
also are you using nodemon?

**Comment by ThriceGood** [comment]
cheers, i use nodemon yes.

**Pull request merged**
